Update issue templates
nakayosh/the-general pull request #8
Opened 2020-08-09 21:46 UTC by chun37

2020-08-10 03:40 UTC, neet commented
チェック事項はPRテンプレの方に書いた方がいいかも

2020-08-10 03:45 UTC, chun37 commented
> チェック事項はPRテンプレの方に書い

fixed

2020-08-10 03:46 UTC, neet commented
下記忘れっぽいのでIssue概要にcloses書いておいた　

2020-08-10 03:50 UTC, chun37 commented
右側の所に linked issues ってあるじゃん
あれ設定してるから良いかなって思ってた
まぁ書いておいたほうがわかりやすいのはある

2020-08-10 03:50 UTC, neet commented
> linked issues
みてなかった

2020-08-10 03:52 UTC, chun37 commented
CONTRIBUTING.md って issue 立てるときと、PR 立てる時に上に出るらしい
まぁ readme に書いておいても損は無いか

2020-08-10 03:53 UTC, neet requested changes

2020-08-10 03:53 UTC, neet commented on .github/ISSUE_TEMPLATE/custom.md
> +
これいる？　雛形がのこってるよな気がする

2020-08-10 03:53 UTC, neet commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
事前設定、コマンドのいみがよくわからない

2020-08-10 03:54 UTC, neet commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
（わかるようなタイトルにしてくださいという意味です）

2020-08-10 03:56 UTC, chun37 commented on .github/ISSUE_TEMPLATE/custom.md
> +
GitHub の Settings から追加できる奴を適当に追加してやってしまっていた。
削除します m( _ _ )m

2020-08-10 03:57 UTC, chun37 commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
bot なのでコマンドのヘルプテキスト的なのが必要だと思った
引数とか

事前設定は #6 の IFTTT の設定が必須とか、そういう情報がほしかった
デプロイしても動かないとかが起きそうなので

2020-08-10 03:58 UTC, neet commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
「コマンドの使い方」「レビュー時の設定方法」って愚直に書くんでいいとおもいます

2020-08-10 03:59 UTC, chun37 commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
OK
修正します

2020-08-10 03:59 UTC, neet commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
設定に関しては詳細に方に書くんでもいい気がするなぁ

2020-08-10 04:00 UTC, chun37 commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
詳細の項目まで決めるのはなんか、自由度が無いなと思ってしまった
詳細は思い思いの書き方で書いてほしいなと思ってた

2020-08-12 18:24 UTC, chun37 commented on .github/PULL_REQUEST_TEMPLATE.md
> +### コマンド
文言は修正しました。
設定の場所についてはそのままです。

2020-08-12 18:38 UTC, neet submitted a review, later dismissed

2020-08-15 02:09 UTC, neet approved these changes
LGTM

2020-08-15 02:10 UTC, merged